<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.sakaiproject</groupId>
    <artifactId>master</artifactId>
    <version>27-SNAPSHOT</version>
    <relativePath>../master/pom.xml</relativePath>
  </parent>

  <name>Sakai Login History</name>
  <groupId>org.sakaiproject.loginhistory</groupId>
  <artifactId>login-history</artifactId>
  <packaging>pom</packaging>

  <modules>
    <module>api</module>
    <module>impl</module>
  </modules>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.sakaiproject.loginhistory</groupId>
        <artifactId>login-history-api</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.mongodb</groupId>
        <artifactId>mongodb-driver-sync</artifactId>
        <version>${sakai.mongodb.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>
